import Head from 'next/head'
import Image from 'next/image'
import Center from '../components/Center/Center'
import Right from '../components/Right/Right'
import Sidebar from '../components/Sidebar/Sidebar'


export default function Home() {
  return (
    <div className=" h-screen overflow-hidden">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex'>
        <Sidebar/>
        <Center/>
        <Right/>
      </main>
      
    </div>
  )
}
